# Generated by Django 4.1.7 on 2023-04-26 17:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import imdb_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('birth_year', models.IntegerField()),
            ],
            options={
                'db_table': 'actors',
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('birth_year', models.IntegerField()),
            ],
            options={
                'db_table': 'directors',
            },
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='movie',
            name='duration_in_min',
            field=models.FloatField(blank=True, db_column='duration', null=True),
        ),
        migrations.CreateModel(
            name='Oscar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomination_type', models.CharField(choices=[('best_picture', 'Best picture'), ('international_feature', 'International Feature'), ('documentary_short', 'Documentary Short'), ('documentary', 'Documentary'), ('animated', 'Animated'), ('animated_short', 'Animated Short'), ('adapted_screenplay', 'Adapted Screenplay'), ('original_screenplay', 'Original Screenplay'), ('production_design', 'Production Design'), ('cinematography', 'Cinematography'), ('costume_design', 'Costume Design'), ('achievement_in_sound', 'Achievement in sound'), ('live_action_short', 'Live Action Short'), ('original', 'Original'), ('visual_effect', 'Visual Effect'), ('film_editing', 'Film Editing'), ('makeup_and_hairstyling', 'Makeup and hairstyling'), ('actress_supporting_role', 'Actress in supporting role'), ('actor_supporting_role', 'Actor in supporting role'), ('actress_leading_role', 'Actress in leading role'), ('actor_leading_role', 'Actor in leading role'), ('director', 'Director')], max_length=128)),
                ('year', models.DateField(validators=[django.core.validators.MinValueValidator(1800), imdb_app.validators.validate_year_before_now])),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='imdb_app.actor')),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='imdb_app.director')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='imdb_app.movie')),
            ],
            options={
                'db_table': 'oscars',
            },
        ),
        migrations.CreateModel(
            name='MovieActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField()),
                ('main_role', models.BooleanField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdb_app.actor')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdb_app.movie')),
            ],
            options={
                'db_table': 'movie_actors',
            },
        ),
    ]
