# Generated by Django 4.1.7 on 2023-04-26 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_app', '0003_movie_director'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oscar',
            name='year',
        ),
    ]
