# Generated by Django 4.1.7 on 2023-04-26 17:39

import django.core.validators
from django.db import migrations, models
import imdb_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_app', '0004_remove_oscar_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='oscar',
            name='year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1929), imdb_app.validators.validate_year_before_now]),
        ),
    ]
