# Generated by Django 4.1.7 on 2023-04-26 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imdb_app', '0005_oscar_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oscar',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='movie',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='oscar',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='oscars', to='imdb_app.movie'),
        ),
    ]
